version: "3.9"
services:
  venv-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/venv-debug:${TAG}
    ports:
      - 6502:6502
      - 6512:6512

  venv:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/venv:${TAG}
