version: "3.9"
services:
  ghjgh-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/ghjgh-debug:${TAG}
    ports:
      - 6502:6502
      - 6512:6512
    
  ghjgh:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/ghjgh:${TAG}
